is_left_camera: false

frame_rate: &frame_rate 10.0

# Strobe and trigger Settings
trigger_selector: "FrameStart"
trigger_source: "Line3"
trigger_activation_mode: "FallingEdge"
# enable_strobe: false
enable_trigger: true
# trigger_source: gpio3

# strobe_source: gpio1

# Diagnostics configuration:
desired_freq: *frame_rate
