frame_rate: &frame_rate 10.0

# Strobe and trigger Settings
enable_strobe: false
enable_trigger: true
trigger_source: gpio3

strobe_source: gpio1

# Diagnostics configuration:
desired_freq: *frame_rate
